/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        soft: "0 10px 30px rgba(15, 23, 42, 0.08)",
      },
      spacing: {
        "container-margin": "20px",
        gutter: "16px",
        md: "24px",
        lg: "40px",
        base: "8px",
        sm: "12px",
        xl: "64px",
        xs: "4px",
        // Admin Dashboard custom spacing
        "container-max": "1280px",
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "64px",
      },
      colors: {
        brand: {
          50: "#eff6ff",
          500: "#2563eb",
          600: "#1d4ed8",
          700: "#1e40af",
        },
        "error-container": "#ffdad6",
        "on-tertiary-container": "#23373a",
        "tertiary-fixed-dim": "#b4cbce",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d3e2ed",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#091f21",
        "on-primary": "#ffffff",
        background: "#f7f9fb",
        "on-error": "#ffffff",
        "on-primary-container": "#00375a",
        "primary-container": "#00a3ff",
        "on-secondary": "#ffffff",
        primary: "#00629d",
        "on-secondary-container": "#56656e",
        "on-surface": "#191c1e",
        outline: "#6f7883",
        "secondary-fixed": "#d6e5ef",
        surface: "#f7f9fb",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#bac9d3",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0f1d25",
        "primary-fixed": "#cfe5ff",
        "surface-tint": "#00629d",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#98cbff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3b4951",
        "on-primary-fixed": "#001d33",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#3f4852",
        "on-primary-fixed-variant": "#004a77",
        "tertiary-fixed": "#d0e7ea",
        "tertiary-container": "#8aa0a3",
        "on-background": "#191c1e",
        secondary: "#526069",
        "outline-variant": "#bec7d4",
        "on-tertiary-fixed-variant": "#364a4d",
        "primary-fixed-dim": "#98cbff",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#4d6265",

        // Admin Dashboard custom colors (Dark Theme tokens)
        "dash-bg": "#0f131c",
        "dash-surface": "#0f131c",
        "dash-surface-dim": "#0f131c",
        "dash-surface-container": "#1c1f29",
        "dash-surface-container-low": "#181b25",
        "dash-surface-container-high": "#262a34",
        "dash-surface-container-highest": "#31353f",
        "dash-surface-container-lowest": "#0a0e17",
        "dash-primary": "#dbfcff",
        "dash-primary-fixed-dim": "#00dbe9",
        "dash-primary-container": "#00f0ff",
        "dash-on-primary": "#00363a",
        "dash-on-surface": "#dfe2ef",
        "dash-on-surface-variant": "#b9cacb",
        "dash-secondary-container": "#0056fd",
        "dash-secondary": "#b6c4ff",
        "dash-on-secondary": "#00277f",
        "dash-error": "#ffb4ab",
        "dash-error-container": "#93000a",
      },
      fontFamily: {
        "utility-mono": ["JetBrains Mono"],
        "headline-md": ["Sora"],
        "body-lg": ["Inter"],
        "headline-lg": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "display-xl": ["Sora"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "utility-mono": ["12px", { lineHeight: "1", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
