/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        soft: "0 10px 30px rgba(15, 23, 42, 0.08)",
      },
      spacing: {
        "container-margin": "20px",
        gutter: "16px",
        md: "24px",
        lg: "40px",
        base: "8px",
        sm: "12px",
        xl: "64px",
        xs: "4px",
      },
      colors: {
        brand: {
          50: "#eff6ff",
          500: "#2563eb",
          600: "#1d4ed8",
          700: "#1e40af",
        },
        "error-container": "#ffdad6",
        "on-tertiary-container": "#23373a",
        "tertiary-fixed-dim": "#b4cbce",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d3e2ed",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#091f21",
        "on-primary": "#ffffff",
        background: "#f7f9fb",
        "on-error": "#ffffff",
        "on-primary-container": "#00375a",
        "primary-container": "#00a3ff",
        "on-secondary": "#ffffff",
        primary: "#00629d",
        "on-secondary-container": "#56656e",
        "on-surface": "#191c1e",
        outline: "#6f7883",
        "secondary-fixed": "#d6e5ef",
        surface: "#f7f9fb",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#bac9d3",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0f1d25",
        "primary-fixed": "#cfe5ff",
        "surface-tint": "#00629d",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#98cbff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3b4951",
        "on-primary-fixed": "#001d33",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#3f4852",
        "on-primary-fixed-variant": "#004a77",
        "tertiary-fixed": "#d0e7ea",
        "tertiary-container": "#8aa0a3",
        "on-background": "#191c1e",
        secondary: "#526069",
        "outline-variant": "#bec7d4",
        "on-tertiary-fixed-variant": "#364a4d",
        "primary-fixed-dim": "#98cbff",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#4d6265",
      },
    },
  },
  plugins: [],
};
